export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const PURCHARSE_BURGER_START = 'PURCHARSE_BURGER_START';
export const PURCHARSE_BURGER_SUCCESS = 'PURCHARSE_BURGER_SUCCESS';
export const PURCHARSE_BURGER_FAIL = 'PURCHARSE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const NEW_ORDER = 'NEW_ORDER';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const CLEAR_ORDERS = 'CLEAR_ORDERS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT= 'AUTH_LOGOUT';
