export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const PURCHARSE_BURGER_START = 'PURCHARSE_BURGER_START';
export const PURCHARSE_BURGER_SUCCESS = 'PURCHARSE_BURGER_SUCCESS';
export const PURCHARSE_BURGER_FAIL = 'PURCHARSE_BURGER_FAIL';